language: r
cache: packages
r:
  - release

r_check_args: --as-cran

warnings_are_errors: true

sudo: false

notifications:
  email:
    on_success: change
    on_failure: always

osx_image: xcode7

os:
  - linux
  - osx
